In [ ]:
import numpy as np
#columns: [age, math marks, science marks]
data = np.array([
    [18, 85, 90], #Students 1
    [19, 78, 88], #Students 2
    [20, 92, 95], #Students 3
    [21, 80, 85], #Students 4
    [22, 88, 92]  #Students 5
])

**Shape** of the matrix

In [2]:
data.shape

(5, 3)

**Age** average

In [7]:
np.mean(data[:,0])

np.float64(20.0)

Extract **Math** marks of all students

In [8]:
data[:, 1]

array([85, 78, 92, 80, 88])

**Highest Science** marks

In [9]:
np.max(data[:,2])

np.int64(95)

**Details** of students, marks higher than 90 in **maths**

In [12]:
data[data[:, 1] > 90]

array([[20, 92, 95]])

Increase marks of **math** for every student by 5

In [13]:
data[:,1] + 5

array([90, 83, 97, 85, 93])