<h2>Nepal Cricket Score Analyzer</h2>

- Create a NumPy array of 10 match scores
- Find highest score, lowest score, average
- Find matches where Nepal scored above 250
- Normalize all scores between 0 and 1
- Find the index of the highest scoring match
- Calculate standard deviation of scores

In [3]:
import numpy as np
score = np.random.randint(150,320,10)
score

array([257, 267, 250, 297, 212, 182, 224, 190, 316, 198], dtype=int32)

**Highest** and **Lowest** score

In [4]:
score.max(), score.min()

(np.int32(316), np.int32(182))

**Average**

In [5]:
score.mean()

np.float64(239.3)

**Score** above 250

In [6]:
score[score[:] > 250]

array([257, 267, 297, 316], dtype=int32)

**Normalize** all score between 0 and 1

In [7]:
score_norm = (score - score.min()) / (score.max() - score.min())
score_norm

array([0.55970149, 0.63432836, 0.50746269, 0.85820896, 0.2238806 ,
       0.        , 0.31343284, 0.05970149, 1.        , 0.11940299])