In [1]:
import numpy as np
arr = np.array([2, 3, 4, 6, 7, 8, 9, 12, 13, 16, 17, 23, 25, 27, 34, 37, 201])
arr

array([  2,   3,   4,   6,   7,   8,   9,  12,  13,  16,  17,  23,  25,
        27,  34,  37, 201])

**<h5>Calculating and storing percentile</h5>**

In [3]:
Q1 = np.percentile(arr,25)
Q3 = np.percentile(arr,75)

**<h5> Calculating IQR</h5>**

In [6]:
IQR = Q3 - Q1
IQR

np.float64(18.0)

**<h5>Calculating upper fence and lower fence</h5>**

In [7]:
upper_fence = Q3 + (1.5*IQR)
lower_fence = Q1 - (1.5*IQR)

**<h5> Removing the outlier element</h5>**

In [11]:
l = []
for i in arr:
    if i <= upper_fence and i >= lower_fence:
        l.append(i)
arr2 = np.array(l)

In [12]:
print(arr)
print(arr2)

[  2   3   4   6   7   8   9  12  13  16  17  23  25  27  34  37 201]
[ 2  3  4  6  7  8  9 12 13 16 17 23 25 27 34 37]
