# Summary of Functions Below

This notebook demonstrates common NumPy utilities used in the cells below:

- `import numpy as np`: import alias for NumPy.
- Random generators: `np.random.random(size)`, `np.random.normal(size)`, `np.random.rand(...)` — uniform, normal, and multi-dimensional random samples.
- `np.arange(start, stop, step)`: create ranges (examples: `np.arange(10)`, `np.arange(5, 10)`, `np.arange(0, 1, 0.1)`).
- `reshape()`: change array dimensions (e.g., `np.arange(10).reshape(2, 5)`).
- `np.linspace(start, stop, num, endpoint=True)`: evenly spaced values.
- Creation helpers: `np.zeros()`, `np.ones()`, `np.empty()` with optional `dtype` to control memory.
- Identity matrices: `np.identity(n)`, `np.eye(N, M, k)`.
- Simple Python example: string indexing (`"Hello world"[6]`).

Use these functions to create, sample, reshape, and inspect arrays for numerical workflows.

In [1]:
import numpy as np

**Random**


In [2]:
np.random.random(size=2)

array([0.59275544, 0.58999985])

In [3]:
np.random.normal(size=2)

array([-1.02551937, -1.37668615])

In [4]:
np.random.rand(2, 4)

array([[0.81258586, 0.99201401, 0.31443699, 0.38773797],
       [0.45545669, 0.26441827, 0.25923787, 0.4736267 ]])

**arange**

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [8]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

**Reshape**

In [9]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

**Linspace**

In [11]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

**Zeros, Ones, Empty**

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((3, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

**Identity** and **Eye**

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.eye(8, 4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
"Hello world"[6]

'w'