In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([4, 5, 6, 7, 8, 9])

**Subtraction**

In [2]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

**Multiplication**

In [ ]:
arr1 * arr2 # vector multiplication (element-wise)

array([ 4, 10, 18, 28, 40, 54])

In [4]:
arr1 * 2 # scalar multiplication

array([ 2,  4,  6,  8, 10, 12])

**Boolean Operations**

In [5]:
arr1 > 3

array([False, False, False,  True,  True,  True])

**Dot Product**

In [6]:
arr3 = np.arange(6).reshape(2, 3)
arr4 = np.arange(6, 12).reshape(3, 2)
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])