In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([4, 5, 6, 7, 8, 9])

**Subtraction**

In [2]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

**Multiplication**

In [3]:
arr1 * arr2

array([ 4, 10, 18, 28, 40, 54])

In [4]:
arr1 * 2 # scalar multiplication

array([ 2,  4,  6,  8, 10, 12])