In [1]:
import numpy as np
arr = np.array([[6, 7], [8, 9], [10, 11]])

In [2]:
arr

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
arr.ndim

2

**Ravel** -> Converts higher dimensional (2D, 3D, 4D...) arrays into 1D array

In [4]:
arr.ravel()

array([ 6,  7,  8,  9, 10, 11])

**Transpose**

In [5]:
arr.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [11]:
arr1 = np.arange(6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr2 = np.arange(12, 18).reshape(2, 3)
arr2

array([[12, 13, 14],
       [15, 16, 17]])

**Stacking** -> Stacking is the process of joining arrays along a new axis.

In [ ]:
np.hstack((arr1, arr2)) # Horizontal stacking

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [13]:
np.vstack((arr1, arr2)) # Vertical stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])