In [1]:
import numpy as np
arr = np.array([[6, 7], [8, 9], [10, 11]])

In [2]:
arr

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
arr.ndim

2

**Ravel** -> Converts higher dimensional (2D, 3D, 4D...) arrays into 1D array

In [4]:
arr.ravel()

array([ 6,  7,  8,  9, 10, 11])

**Transpose**

In [5]:
arr.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])