# Array Reshaping Operations

This notebook explores in-depth array reshaping and manipulation techniques:

- **ndim**: Check the number of dimensions of an array
- **ravel()**: Flatten multidimensional arrays into 1D
- **transpose()**: Swap rows and columns (or reorder axes)
- **hstack()**: Stack arrays horizontally (column-wise)
- **vstack()**: Stack arrays vertically (row-wise)
- **hsplit()**: Split an array horizontally into sub-arrays
- **vsplit()**: Split an array vertically into sub-arrays

These operations are essential for reshaping data to fit different computational needs.

In [1]:
import numpy as np
arr = np.array([[6, 7], [8, 9], [10, 11]])

In [2]:
arr

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
arr.ndim

2

**Ravel** -> Converts higher dimensional (2D, 3D, 4D...) arrays into 1D array

In [4]:
arr.ravel()

array([ 6,  7,  8,  9, 10, 11])

**Transpose**

In [5]:
arr.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [11]:
arr1 = np.arange(6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr2 = np.arange(12, 18).reshape(2, 3)
arr2

array([[12, 13, 14],
       [15, 16, 17]])

**Stacking** -> Stacking is the process of joining arrays along a new axis.

In [12]:
np.hstack((arr1, arr2)) # Horizontal stacking

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [13]:
np.vstack((arr1, arr2)) # Vertical stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

**Splitting** -> Splitting is the process of dividing an array into multiple sub-arrays.

In [21]:
np.hsplit(arr1, 3) # Horizontal splitting

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [22]:
np.vsplit(arr1, 2) # Vertical splitting

[array([[0, 1, 2]]), array([[3, 4, 5]])]