In [5]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5, 2])

# acessing the elements in the array 
print(a[0], a[1])

1 2


In [11]:
a[::2]

array([1, 3])

In [6]:
a[1:3]

array([2, 3])

In [10]:
# Multi indexing
b[[0, 2, -1]]

array([0., 1., 2.])