# NumPy — Indexing and Slicing
NumPy arrays support powerful indexing and slicing operations that are similar to Python lists but more flexible and efficient. Below are the common techniques and examples.

- **Indexing**: Access single elements with integer indices, e.g. `arr[0]` or `arr[1, 2]` for a 2D array.
- **Slicing**: Extract subarrays using `start:stop:step`, e.g. `arr[1:5]`, `arr[:, :3]`, or `arr[::2]`.
- **Boolean indexing**: Use a boolean mask to select elements, e.g. `arr[arr > 0]`.
- **Fancy (integer) indexing**: Use integer arrays to pick arbitrary elements, e.g. `arr[[0, 2, 4]]` or `arr[[0,1],[2,3]]`.


In [1]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [2]:
A[0]

array([1, 2, 3])

In [3]:
A[1][0]

np.int64(4)

**Multi dimensional selection** A[d1, d2, d3, d4]

In [4]:
A[1, 0]

np.int64(4)

**Selecting whole dimensions**


In [5]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

**Every row** A[:, 0:2] (or A[:, :2]) - selects all rows and the first two columns.

In [6]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

**Select** two rows and two columns

In [7]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

**Select** 1 row and 1 column

In [8]:
A[:2, 2:]

array([[3],
       [6]])

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Replacing** a row in matrices

In [10]:
A[1] = np.array([10,10,10])

In [11]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

**indexed** assignment (using integer indexing)

In [12]:
A[2] = 99

In [13]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])