# NumPy — Broadcasting and Vectorization

## Broadcasting

Broadcasting is NumPy's way of making arrays with different shapes work together in arithmetic operations. Instead of manually expanding smaller arrays, NumPy compares the shapes from right to left and applies rules that allow compatible dimensions to be combined.

Broadcasting is especially useful when one array contains a single value, a row, or a column that should be applied across a larger array. This keeps code shorter, clearer, and much faster than using Python loops.

### Why it matters
- Reduces the need for explicit loops
- Makes array math cleaner and more readable
- Improves performance by letting NumPy handle operations in compiled code

### Common idea
A smaller array can be stretched conceptually across a larger array if its dimensions are either equal or one of them is `1`.

## Vectorization

Vectorization means expressing calculations on whole arrays at once instead of processing elements one by one in Python. NumPy uses optimized low-level routines for these operations, so vectorized code is usually much faster than manual loops.

### Benefits of vectorization
- Better performance
- Less verbose code
- Easier to read and maintain
- Makes use of NumPy's optimized internal implementation

## Broadcasting vs Vectorization

These concepts often appear together:
- **Broadcasting** handles shape compatibility
- **Vectorization** handles performing operations on arrays efficiently

In practice, broadcasting lets vectorized expressions work naturally across arrays of different shapes.

## Key Points

- Broadcasting does not always copy data; it often works conceptually without creating full expanded arrays.
- Not all shapes are compatible, so the dimensions must follow broadcasting rules.
- Vectorized operations are preferred over loops whenever possible in numerical computing with NumPy.
- Together, broadcasting and vectorization are a major reason NumPy is efficient for data processing and scientific computing.

In [2]:
import numpy as np
a = np.arange(4)

In [ ]:
a   

array([0, 1, 2, 3])

**Vectorized Sum**

In [4]:
a + 10

array([10, 11, 12, 13])

**Vectorized Multiply**

In [5]:
a * 10

array([ 0, 10, 20, 30])

In [6]:
a 

array([0, 1, 2, 3])

Actually modifying the **Array* `a`

In [7]:
a += 100

In [8]:
a

array([100, 101, 102, 103])