# NumPy Boolean Arrays

Boolean arrays are arrays whose elements are either `True` or `False`. In NumPy, they are commonly created by comparing numeric arrays with conditions such as greater than, less than, or equality.

A boolean array is often called a **mask** because it acts like a filter over another array:
- `True` means keep/select the element.
- `False` means ignore/remove the element.

## Why Boolean Arrays Are Useful

- They allow condition-based selection without manual loops.
- They make data filtering readable and concise.
- They are fast because operations are performed in optimized NumPy routines.

## Typical Operations with Boolean Arrays

- **Filtering**: Select elements that satisfy a condition.
- **Counting conditions**: Measure how many elements meet a rule.
- **Combining conditions**: Build complex filters using logical operations (AND, OR, NOT).
- **Conditional replacement**: Update values where a condition is true.

## Logical Combination of Masks

Multiple conditions can be merged into one mask to express complex criteria. This is commonly used in data cleaning and preprocessing, where you want to isolate invalid, missing, or out-of-range values.

## Important Concept

Boolean indexing usually returns a new array containing matching elements. This behavior is different from simple slicing, which often returns a view. Understanding this distinction helps avoid confusion when modifying data.

## Practical Perspective

Boolean arrays are one of NumPy's most important tools for analytical workflows. They let you describe *what* data you want in a declarative way, making array manipulation more expressive, maintainable, and efficient.

In [1]:
import numpy as np
a = np.arange(4)

In [2]:
a

array([0, 1, 2, 3])

In [3]:
a[0], a[-1]

(np.int64(0), np.int64(3))

In [5]:
a[[0, -1]]

array([0, 3])

**Boolean* arrays indexing/selecting

In [6]:
a[[True, False, False, True]]

array([0, 3])

In [7]:
a >= 2

array([False, False,  True,  True])

**Putting** only the elements which are greater or equal to 2, using boolean operators

In [8]:
a[a >= 2]

array([2, 3])

In [9]:
np.mean(a)

np.float64(1.5)

In [11]:
a[a > np.mean(a)]

array([2, 3])