# NumPy — Linear Algebra

Linear algebra is the branch of mathematics that studies vectors, matrices, and the operations performed on them. It is one of the foundations of scientific computing, machine learning, graphics, and data analysis.

In NumPy, linear algebra is represented mainly through arrays. One-dimensional arrays can be treated as vectors, while two-dimensional arrays represent matrices. Higher-dimensional arrays can be used for more advanced tensor-like structures.

## Why It Matters

- It helps describe and solve systems of equations.
- It is essential for transformations, projections, and rotations.
- It powers many algorithms in machine learning and numerical analysis.
- It allows efficient computation on large structured datasets.

## Common Concepts

**Vector**: An ordered list of numbers that can represent quantities such as direction, position, or features.

**Matrix**: A rectangular grid of numbers used to represent linear transformations or collections of data.

**Dot Product**: A measure of similarity between vectors, often used in projections and scoring.

**Matrix Multiplication**: A core operation that combines transformations or maps one vector space into another.

**Transpose**: Flips a matrix over its diagonal, switching rows and columns.

**Determinant**: A scalar value that provides information about a square matrix, including whether it is invertible.

**Inverse**: A matrix that reverses the effect of another matrix, when it exists.

## Practical Perspective

Linear algebra in NumPy is used to express mathematical ideas in a compact and efficient way. Instead of working with formulas element by element, NumPy lets you operate on entire vectors and matrices at once, making code shorter, faster, and easier to reason about.

## Key Idea

When working with linear algebra in NumPy, it is important to understand the shapes of arrays, because the meaning of an operation depends on whether you are working with a vector, matrix, or higher-dimensional array.

In [1]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ])

In [2]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

dot product is a fundamental operation in linear algebra, and it can be computed in NumPy using either the `dot` function or the `@` operator.

In [3]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

@ is a more concise way to perform matrix multiplication, while `dot` can be used for both dot products and matrix multiplication depending on the input shapes.

In [4]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

**Transpose** is a common operation that can be performed using the `.T` attribute of a NumPy array.

In [5]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Matrix multiplication of B transpose and A

In [7]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])